server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/supermercado?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: Jorge
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: update   # opções: validate | update | create | create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
